cache:
  directories:
  - "$HOME/.pub-cache"
jobs:
  include:
  - stage: deployAPK
    os: linux
    language: android
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28
      - sys-img-armeabi-v7a-google_apis-25
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-google-android-support
    jdk: oraclejdk8
    sudo: false
#    env: APK_OUTPUT=build/app/outputs/apk/release/app-arm64-v8a-release.apk
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - git clone https://github.com/flutter/flutter.git
    - git lfs install
    - git clone https://github.com/OpenIoTHub/flutter_natcloud_service.git ../flutter_natcloud_service
#
    # build aar
    - git clone https://github.com/OpenIoTHub/OpenIoTHubService.git
    # download golang
    - wget -q https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz
    - sudo tar -zxf go1.14.1.linux-amd64.tar.gz -C /usr/local
    - export GOROOT=/usr/local/go
    - export GOPATH=/home/travis/go
    - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
    - go version
    # download ndk
    - wget -q https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
    - sudo unzip android-ndk-r21-linux-x86_64.zip -d $ANDROID_HOME
    - export ANDROID_NDK_HOME=$ANDROID_HOME/android-ndk-r21
    # install gomobile
    - go get golang.org/x/mobile/cmd/gomobile
    - go get golang.org/x/mobile/cmd/gobind
    - gomobile init
    - gomobile version
    - pwd
    #    - find / client.aar
    - cd OpenIoTHubService/mobile
    - gomobile bind -target=android
    - cd ../..
    - rm -rf android/app/libs/*.aar
    - ls -a
    - cp ./OpenIoTHubService/mobile/explorer.aar android/app/libs
    # build aar over
    script:
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "platforms;android-29"
    - mkdir release
    - ./flutter/bin/flutter doctor -v
#    - ./flutter/bin/flutter version v1.9.0"
    - ./flutter/bin/flutter pub get
    - ./flutter/bin/flutter -v build apk --release --split-per-abi
    - mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk ./release
    - mv build/app/outputs/apk/release/app-arm64-v8a-release.apk ./release
    - mv build/app/outputs/apk/release/app-x86_64-release.apk ./release
    - ./flutter/bin/flutter -v build apk --release
    - mv build/app/outputs/apk/release/app-release.apk ./release
    - ./flutter/bin/flutter --version
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: FJ/9t6TilxefjtU64QVjKea/qR+cLUv+dOti+3aspzudcUGWuCyUOKudhtc+PKv1B7pzjrwcAm4iNs4DD4Mm/DFdRmLgjL9+Xg8RLq6pEanr+apc8qG/nRA+NSD5F9Zkj7I4cVp4X2GhXvGJ1kMxt34SazcskdQJwnbLKcVQwXlWYelf1XbI24EZJHNyA+k1Oj980zG5WE2DJ4ETGHqzjB2NutDh1OAI64l4ZUv1/VEysJejsW1popoGbu0CN7/UY6Oedzqiv1NEbcBIez7VzN3lqFwTpfyQB/yglj6yXKuNutJjlvgjOy8a/wD4m9SGlZjrQ30ebB8Pol906T98qqyg/cT7aBc0GZZ0g19hvbheJwyq21yVy5Mf/VvQa389Ud0Kk27SmYDvyPhDyIB4vhT8pC0qDAnwaIEk+q1FkriMgtdrC+oCBuUe9bAeVymXSDc9yypaKbB8KU9xpLKOeznKe/cTIToM5TlGjWI0K1amdG/DVItwS5Xxx5sfLIjAoWghlfqdJI/znKLHkKQL4oEx8/pOcY652efFoNK0PBiYc7HMRm8UEQviZCqS9l08HEvtvSI5soyNQ2OOQa8PiD63YznwDemwP8AqUHiJnw7TRuOxhvINfG1eVLYqinPD/NkH9UVdP3eVkmjrkRng2pkYBAavRLyZuLosUFtVhXQ=
      file:
        - release/app-armeabi-v7a-release.apk
        - release/app-arm64-v8a-release.apk
        - release/app-x86_64-release.apk
        - release/app-release.apk
      on:
        tags: true
#  - stage: deployIPA
#    os: osx
#    language: objective-c
#    osx_image: xcode11.2
#    before_script:
#      - brew update
#      - brew install libimobiledevice
#      - brew install ideviceinstaller
#      - brew install ios-deploy
#      - git clone https://github.com/flutter/flutter.git
#      - git clone https://github.com/OpenIoTHub/flutter_natcloud_service.git ../flutter_natcloud_service
#      - tar -xzvf ../flutter_natcloud_service/ios/Frameworks/Explorer.framework/Versions/A/Explorer.tar.gz -C ../flutter_natcloud_service/ios/Frameworks/Explorer.framework/Versions/A
#    script:
#      - gem install cocoapods
#      - pod setup
#      - gem install cocoapods-deintegrate
#      - "./flutter/bin/flutter upgrade"
#      - "./flutter/bin/flutter doctor -v"
#      - "./flutter/bin/flutter precache -a"
#      - "./flutter/bin/flutter pub get"
#      - "./flutter/bin/flutter clean"
#      #    - "./flutter/bin/flutter version v1.9.0"
#      - "./flutter/bin/flutter build ios --debug --no-codesign"
#      - mkdir Runner
#      - mkdir Runner/Payload
#      - cp -r build/ios/iphoneos/Runner.app Runner/Payload/Runner.app
#      - cd Runner
#      - zip -r Runner.ipa Payload
#    deploy:
#      provider: releases
#      skip_cleanup: true
#      api_key:
#        secure: FJ/9t6TilxefjtU64QVjKea/qR+cLUv+dOti+3aspzudcUGWuCyUOKudhtc+PKv1B7pzjrwcAm4iNs4DD4Mm/DFdRmLgjL9+Xg8RLq6pEanr+apc8qG/nRA+NSD5F9Zkj7I4cVp4X2GhXvGJ1kMxt34SazcskdQJwnbLKcVQwXlWYelf1XbI24EZJHNyA+k1Oj980zG5WE2DJ4ETGHqzjB2NutDh1OAI64l4ZUv1/VEysJejsW1popoGbu0CN7/UY6Oedzqiv1NEbcBIez7VzN3lqFwTpfyQB/yglj6yXKuNutJjlvgjOy8a/wD4m9SGlZjrQ30ebB8Pol906T98qqyg/cT7aBc0GZZ0g19hvbheJwyq21yVy5Mf/VvQa389Ud0Kk27SmYDvyPhDyIB4vhT8pC0qDAnwaIEk+q1FkriMgtdrC+oCBuUe9bAeVymXSDc9yypaKbB8KU9xpLKOeznKe/cTIToM5TlGjWI0K1amdG/DVItwS5Xxx5sfLIjAoWghlfqdJI/znKLHkKQL4oEx8/pOcY652efFoNK0PBiYc7HMRm8UEQviZCqS9l08HEvtvSI5soyNQ2OOQa8PiD63YznwDemwP8AqUHiJnw7TRuOxhvINfG1eVLYqinPD/NkH9UVdP3eVkmjrkRng2pkYBAavRLyZuLosUFtVhXQ=
#      file: Runner.ipa
#      on:
#        tags: true
before_install:
- export ANDROID_HOME=/usr/local/android-sdk
- openssl aes-256-cbc -K $encrypted_f0033d4e34c5_key -iv $encrypted_f0033d4e34c5_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar -C ./android
